api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    path_segment_name_generator: 'App\PathResolver\IndonesianUnderscorePathSegmentNameGenerator'
    formats:
        json:
            mime_types: ['application/json']    
        jsonld:
            mime_types: ['application/ld+json']
        html:
            mime_types: ['text/html']
    swagger:
         api_keys:
             apiKey:
                name: Authorization
                type: header
    collection:
        pagination:
            # The default number of items per page.
            items_per_page: 5